# /docker-compose.yml
version: '3.8'
services:
  backend:
    build: ./krisys-backend
    volumes:
      - ./blockchain:/app/blockchain
      - ./krisys-backend:/app  # Hot reload for development
    ports:
      - "5000:5000"
    environment:
      - BLOCKCHAIN_DB_PATH=/app/blockchain.db
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    command: python -m flask run --host=0.0.0.0 --port=5000 --reload

  frontend:
    build: ./krisys-frontend
    volumes:
      - ./krisys-frontend:/app
      - /app/node_modules
      - /app/.next
      - ./blockchain:/app/blockchain # DEV ONLY!!! for admin panel controls
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      # DEV ONLY: provides known station base URL to wallet frontend so trusted stations can be added and removed.
      # In production, station base_url comes from scanned QR code and NEXT_PUBLIC_STATION_API is not used at all.
      - NEXT_PUBLIC_STATION_API=http://localhost:6001
    # Development command with hot reload
    # command: npm start
    # For production, comment above and uncomment below:
    command: npm run dev
    depends_on:
      - backend
  station:
    build: 
      context: ./krisys-backend
      dockerfile: ./device-offline-server/Dockerfile
    ports:
      - "6001:5000"
      - "7000:7000"
    environment:
      - FLASK_ENV=development
      - CENTRAL_API_URL=http://backend:5000
      - STATION_AUTO_SYNC=1
    volumes:
      # DEV: local folder where station stores its own mesh DB/cache
      - ./krisys-backend/device-offline-server/station-data:/app/data
      - ./krisys-backend/device-offline-server/rtc-host:/app/rtc-host
    depends_on:
      - backend
  relay:
    build: 
      context: ./krisys-backend
      dockerfile: ./relay-offline-server/Dockerfile
    ports:
      - "6002:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      # DEV: local folder where dumb relay stores its own mesh DB/cache
      - ./krisys-backend/relay-offline-server/relay-data:/app/data
    depends_on:
      - backend
  station_camp:
    build: 
      context: ./krisys-backend
      dockerfile: ./device-offline-server/Dockerfile
    container_name: krisys_station_camp
    ports:
      - "6003:5000"
    environment:
      - FLASK_ENV=development
      - CENTRAL_API_URL=http://backend:5000
      - STATION_AUTO_SYNC=1
      - STATION_ID=CAMP_CENTRAL
    volumes:
      - ./krisys-backend/camp_central/station-data:/app/data
    depends_on:
      - backend
  station_frontend:
    build:
      context: ./krisys-backend/device-offline-server/station-frontend
    ports:
      - "6600:3000"
    environment:
      - NEXT_PUBLIC_STATION_API=http://localhost:6001
    volumes:
      - ./krisys-backend/device-offline-server/station-frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - station